# Generated by Django 4.2.13 on 2024-07-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0006_alter_tweet_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='photo',
            new_name='image',
        ),
    ]
